# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndianaLidar
                                 A QGIS plugin
 This plugin helps you access Indiana LiDAR data products.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-02
        copyright            : (C) 2023 by Jinha Jung
        email                : jinha@purdue.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndianaLidar class from file IndianaLidar.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indiana_lidar import IndianaLidar
    return IndianaLidar(iface)
